name: Grab deps test and publish

on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - master

jobs:

  tests:
    name: JS test with Mocha
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # See {https://github.com/marketplace/actions/setup-node-js-for-use-with-actions}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.6'

      - name: Install dependencies
        run: npm install

      - name: Build test files
        run: npm run js

      - name: Run test suit
        run: npm test

      - name: Lint check
        run: npm run lint


  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: always()
    needs: [tests]
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  branch-check:
    uses: tarosky/workflows/.github/workflows/check-tag-in-branch.yml@main
    needs: status-check
    with:
      allowed_branch: "master"

  publish:
    name: Publish to npm.js
    runs-on: ubuntu-latest
    needs: branch-check
    if: contains(github.ref, 'tags/')
    environment:
      name: production
      url: https://www.npmjs.com/package/@kunoichi/grab-deps
    steps:
      - uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.6'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $TAG_VERSION"

      - name: Update package.json version
        run: |
          VERSION=${{ steps.extract_version.outputs.VERSION }}
          echo "Updating package.json version to: $VERSION"
          npm version $VERSION --no-git-tag-version
          cat package.json | grep '"version"'

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.KUNOICHI_NPM_ACCESS_TOKEN }}
