name: Publish to npm

on:
  release:
    types: [published]

jobs:

  publish:
    name: Publish to npm.js
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: production
      url: https://www.npmjs.com/package/@kunoichi/grab-deps
    steps:
      - uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.6'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Extract version from release tag
        id: extract_version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version from release: $TAG_VERSION"

      - name: Update package.json version
        run: |
          VERSION=${{ steps.extract_version.outputs.VERSION }}
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          echo "Target version: $VERSION"
          if [ "$CURRENT_VERSION" != "$VERSION" ]; then
            echo "Updating package.json version to: $VERSION"
            npm version $VERSION --no-git-tag-version
          else
            echo "Version is already $VERSION, skipping update"
          fi
          cat package.json | grep '"version"'

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.KUNOICHI_NPM_ACCESS_TOKEN }}
