name: Grab deps test.

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:

  tests:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # See {https://github.com/marketplace/actions/setup-node-js-for-use-with-actions}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.6'

      - name: Install dependencies
        run: npm install

      - name: Run test suit
        run: npm test
