name: Grab deps test.

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:

  tests:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: npm install

      - run: npm test
  # See {https://github.com/marketplace/actions/setup-node-js-for-use-with-actions}
