name: Test Suite

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: JS test with Mocha
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # See {https://github.com/marketplace/actions/setup-node-js-for-use-with-actions}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.6'

      - name: Install dependencies
        run: npm install

      - name: Build test files
        run: npm run build:js

      - name: Run test suit
        run: npm test

      - name: Lint check
        run: npm run lint

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: always()
    needs: [tests]
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
